List<String> alphabet = [
  'Ž - Žena',
  'Z - Zagreb',
  'V - Vino',
  'U - Ulica',
  'T - Tramvaj',
  'Š - Škola',
  'S - Sok',
  'R - Račun',
  'P - Pivo',
  'O - Olovka',
  'Nj - Njemačka',
  'N - Novac',
  'M - More',
  'Lj- Lječnica',
  'L - Limun',
  'K - Kava',
  'J - Jaja',
  'I - Italija',
  'H - Hrvatska',
  'G - Grad',
  'F - Film',
  'E - Euro',
  'Đ - Đak',
  'Dž - Džep',
  'D - Dan',
  'Ć - Ćevapi',
  'Č - Čaj',
  'C - Cigareta',
  'B - Bicikl',
  'A - Ananas',
];

List<String> alphabet_images = [
  // Ž - Žena
  "assets/images/alphabet/lady.jpg",
  "assets/images/alphabet/zagreb.jpg",
  "assets/images/alphabet/wine.webp",
  "assets/images/alphabet/prague_street.jpg",
  "assets/images/alphabet/trams.webp",
  "assets/images/alphabet/school.jpg",
  "assets/images/alphabet/juices.jpg",
  "assets/images/alphabet/receipt.jpg",
  "assets/images/alphabet/beer.webp",
  "assets/images/alphabet/pencil.png",
  "assets/images/alphabet/germany.jpg",
  "assets/images/alphabet/novac.jpg",
  "assets/images/alphabet/sea.jpeg",
  "assets/images/alphabet/african_doctor.jpg",
  "assets/images/alphabet/lemon.webp",
  "assets/images/alphabet/coffee.jpg",
  "assets/images/alphabet/fried_egg.jpg",
  "assets/images/alphabet/ITALY.jpg",
  "assets/images/alphabet/croatia_map.jpg",
  "assets/images/alphabet/grad.jpg",
  "assets/images/alphabet/movie_trailer.jpeg",
  "assets/images/alphabet/euro.jpg",
  "assets/images/alphabet/dak.jpg",
  "assets/images/alphabet/pocket.jpg",
  "assets/images/alphabet/day.jpg",
  "assets/images/alphabet/cevapi.jpg",
  "assets/images/alphabet/caj.jpg",
  "assets/images/alphabet/cigarette.jpg",
  "assets/images/alphabet/bike.png",
  "assets/images/alphabet/ananas.webp",
  // A-ananas
];
